### ISSUE TITLE
About to break clob

### ISSUE THREAD

**Issue by MikeNeilson** [HydrologicEngineeringCenter/cwms-data-api-client#90]
FYI, I'm about to break the clob DTO in data-api. It's the only one that uses "office" instead of "office-id".

I can go ahead and do the fix here, but I wanted to make sure y'all are aware.

**Comment by adamkorynta** [comment]
Clob update has been fixed in PR: https://github.com/HydrologicEngineeringCenter/cwms-data-api-client/pull/97
